Update patch set 3
Patch Set 3:

Moving jetty related dependencies from cps-tbdmt-dependencies to cps-tbdmt-rest module as it was using old versions during runtime causing the below error. 

Application run failed
cps-tbdmt    |
cps-tbdmt    | org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
cps-tbdmt    |  at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:161) ~[spring-boot-2.3.8.RELEASE.jar:2.3.8.RELEASE]
cps-tbdmt    |  at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545) ~[spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
cps-tbdmt    |  at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.8.RELEASE.jar:2.3.8.RELEASE]
cps-tbdmt    |  at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.8.RELEASE.jar:2.3.8.RELEASE]
cps-tbdmt    |  at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot-2.3.8.RELEASE.jar:2.3.8.RELEASE]
cps-tbdmt    |  at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405) ~[spring-boot-2.3.8.RELEASE.jar:2.3.8.RELEASE]
cps-tbdmt    |  at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.3.8.RELEASE.jar:2.3.8.RELEASE]
cps-tbdmt    |  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.8.RELEASE.jar:2.3.8.RELEASE]
cps-tbdmt    |  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.8.RELEASE.jar:2.3.8.RELEASE]
cps-tbdmt    |  at org.onap.cps.tbdmt.Application.main(Application.java:30) ~[classes/:na]
cps-tbdmt    | Caused by: java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
cps-tbdmt    |  at org.eclipse.jetty.servlet.ServletContextHandler.newSecurityHandler(ServletContextHandler.java:335) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
cps-tbdmt    |  at org.eclipse.jetty.servlet.ServletContextHandler.getSecurityHandler(ServletContextHandler.java:396) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
cps-tbdmt    |  at org.eclipse.jetty.servlet.ServletContextHandler.relinkHandlers(ServletContextHandler.java:240) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
cps-tbdmt    |  at org.eclipse.jetty.servlet.ServletContextHandler.<init>(ServletContextHandler.java:162) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
cps-tbdmt    |  at org.eclipse.jetty.webapp.WebAppContext.<init>(WebAppContext.java:278) ~[jetty-webapp-9.4.35.v20201120.jar:9.4.35.v20201120]
cps-tbdmt    |  at org.eclipse.jetty.webapp.WebAppContext.<init>(WebAppContext.java:207) ~[jetty-webapp-9.4.35.v20201120.jar:9.4.35.v20201120]
cps-tbdmt    |  at org.springframework.boot.web.embedded.jetty.JettyEmbeddedWebAppContext.<init>(JettyEmbeddedWebAppContext.java:28) ~[spring-boot-2.3.8.RELEASE.jar:2.3.8.RELEASE]
cps-tbdmt    |  at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.getWebServer(JettyServletWebServerFactory.java:141) ~[spring-boot-2.3.8.RELEASE.jar:2.3.8.RELEASE]
cps-tbdmt    |  at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:178) ~[spring-boot-2.3.8.RELEASE.jar:2.3.8.RELEASE]
cps-tbdmt    |  at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:158) ~[spring-boot-2.3.8.RELEASE.jar:2.3.8.RELEASE]
cps-tbdmt    |  ... 9 common frames omitted
cps-tbdmt    | Caused by: java.lang.reflect.InvocationTargetException: null
cps-tbdmt    |  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
cps-tbdmt    |  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:na]
cps-tbdmt    |  at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:na]
cps-tbdmt    |  at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:na]
cps-tbdmt    |  at org.eclipse.jetty.servlet.ServletContextHandler.newSecurityHandler(ServletContextHandler.java:331) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
cps-tbdmt    |  ... 18 common frames omitted
cps-tbdmt    | Caused by: java.lang.NoClassDefFoundError: org/eclipse/jetty/http/PathMap
cps-tbdmt    |  at org.eclipse.jetty.security.ConstraintSecurityHandler.<init>(ConstraintSecurityHandler.java:68) ~[jetty-security-9.4.35.v20201120.jar:9.4.35.v20201120]
cps-tbdmt    |  ... 23 common frames omitted
cps-tbdmt    | Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.http.PathMap
cps-tbdmt    |  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[na:na]
cps-tbdmt    |  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[na:na]
cps-tbdmt    |  at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[na:na]
cps-tbdmt    |  ... 24 common frames omitted

Patch-set: 3
Reviewer: Gerrit User 5658 <5658@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Reviewer: Gerrit User 6639 <6639@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Reviewer: Gerrit User 6841 <6841@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Reviewer: Gerrit User 7743 <7743@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>